### ISSUE TITLE
PopConfirm not work on AJAX loaded HTML elements

### ISSUE THREAD

**Issue by renat2985** [Ifnot/PopConfirm#19]
PopConfirm not work on AJAX loaded HTML elements please help.

**Comment by Ifnot** [comment]
Hi,

It is normal, as all jquery plugins handle the dom of the page (that's why we use $(document).ready()).

If you want to add PopConfirm behaviour on loaded HTML content you should run another time $('.my-new-content').popConfirm();

Usefull trick : Do all your dom enhanding stuff (like popconfirm) into a js function with a selector. So you can use the same piece of code for startup (and all your document), and for async content.
